apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-nonroot
  name: nginx-nonroot
spec:
  securityContext:
    runAsNonRoot: true
  containers:
  - image: nginx:1.12
    name: nginx-nonroot
  dnsPolicy: ClusterFirst
  restartPolicy: Never
